--RESET
DROP TABLE FACT_SALARYPAID CASCADE CONSTRAINTS;
DROP TABLE FACT_SUBTYPES CASCADE CONSTRAINTS;
DROP TABLE FACT_READING CASCADE CONSTRAINTS;
DROP TABLE DIM_STATION CASCADE CONSTRAINTS;
DROP TABLE DIM_LOCATION CASCADE CONSTRAINTS;
DROP TABLE DIM_CUSTOMER CASCADE CONSTRAINTS;
DROP TABLE DIM_SUBSCRIPTION CASCADE CONSTRAINTS;
DROP TABLE DIM_SALARY CASCADE CONSTRAINTS;
DROP TABLE DIM_EMPLOYEE CASCADE CONSTRAINTS;
DROP TABLE DIM_TIME CASCADE CONSTRAINTS;
DROP TABLE DIM_TIME_SALARY CASCADE CONSTRAINTS;

--STAR SCHEME 1
CREATE TABLE DIM_STATION (
    "STATION_ID" NUMBER(6,0) PRIMARY KEY,
    "ISACTIVE" NUMBER(1,0)
  );

CREATE TABLE DIM_LOCATION (
  "LOCATION_ID" NUMBER(6, 0) PRIMARY KEY,
  "LOCATION_NAME"  VARCHAR(25)
);

CREATE TABLE DIM_TIME (
  "TIME_ID" DATE PRIMARY KEY,
  "HOUR" NUMBER(6, 0),
  "DAY" NUMBER(6, 0),
  "WEEK" NUMBER(6, 0),
  "MONTH" NUMBER(6, 0),
  "YEAR" NUMBER(6, 0)
);

CREATE TABLE DIM_TIME_SALARY (
  "TIME_ID" DATE PRIMARY KEY,
  "HOUR" NUMBER(6, 0),
  "DAY" NUMBER(6, 0),
  "WEEK" NUMBER(6, 0),
  "MONTH" NUMBER(6, 0),
  "YEAR" NUMBER(6, 0)
);

CREATE TABLE FACT_READING (
  "STATION_ID" NUMBER(6,0),
  "LOCATION_ID" NUMBER(6,0),
  "TIME_ID" DATE,
  "AVG_AIRPRESSURE" NUMBER(8,2),
  "AVG_AMBIENTLIGHT" NUMBER(8,2),
  "AVG_HUMIDITY" NUMBER(8,2),
  "AVG_TEMP" NUMBER(8,2),
  CONSTRAINT FACT_PK PRIMARY KEY (TIME_ID, LOCATION_ID, STATION_ID)
);


ALTER TABLE FACT_READING
ADD CONSTRAINT STATION_FK
FOREIGN KEY("STATION_ID")
REFERENCES DIM_STATION("STATION_ID");

ALTER TABLE FACT_READING
ADD CONSTRAINT LOCATION_FK
FOREIGN KEY("LOCATION_ID")
REFERENCES DIM_LOCATION("LOCATION_ID");

ALTER TABLE FACT_READING
ADD CONSTRAINT TIMEP_FK
FOREIGN KEY("TIME_ID")
REFERENCES DIM_TIME("TIME_ID");

CREATE INDEX IDX_FK_STATIONID ON FACT_READING(STATION_ID);
CREATE INDEX IDX_FK_LOCATIONID ON FACT_READING(LOCATION_ID);
CREATE INDEX IDX_FK_TIMEID_READING ON FACT_READING(TIME_ID);

--STAR SCHEME 2

CREATE TABLE DIM_SUBSCRIPTION (
  "SUB_ID" NUMBER(6,0) PRIMARY KEY,
  "NAME" VARCHAR(12)
);

CREATE TABLE DIM_CUSTOMER (
  "PERSON_ID" NUMBER(6,0) PRIMARY KEY,
  "BIRTH_DATE" DATE
);

CREATE TABLE FACT_SUBTYPES (
  "PERSON_ID" NUMBER(6,0),
  "SUB_ID" NUMBER(6,0),
  CONSTRAINT SUB_PK PRIMARY KEY(PERSON_ID,SUB_ID)
);

ALTER TABLE FACT_SUBTYPES
ADD CONSTRAINT SUB_FK
FOREIGN KEY ("SUB_ID")
REFERENCES DIM_SUBSCRIPTION("SUB_ID");

ALTER TABLE FACT_SUBTYPES
ADD CONSTRAINT PERSON_FK
FOREIGN KEY ("PERSON_ID")
REFERENCES DIM_CUSTOMER("PERSON_ID");

CREATE INDEX IDX_FK_SUBID ON FACT_SUBTYPES(SUB_ID);
CREATE INDEX IDX_FK_PERSONID_SUB ON FACT_SUBTYPES(PERSON_ID);

-- STAR SCHEME 3

CREATE TABLE DIM_SALARY (
  "SALARY_ID" NUMBER(6,0) PRIMARY KEY,
  "AMOUNT" NUMBER(10,2)
);

CREATE TABLE DIM_EMPLOYEE (
  PERSON_ID NUMBER(6,0) PRIMARY KEY,
  POSITION_TYPE CHAR(1)
);

CREATE TABLE FACT_SALARYPAID (
  "PERSON_ID" NUMBER(6,0),
  "SALARY_ID" NUMBER(6,0),
  "TIME_ID" DATE,
  CONSTRAINT SALARYPAID_PK
  PRIMARY KEY("PERSON_ID", "SALARY_ID", "TIME_ID")
);

ALTER TABLE FACT_SALARYPAID
ADD CONSTRAINT EMPLOYEE_FK
FOREIGN KEY ("PERSON_ID")
REFERENCES DIM_EMPLOYEE("PERSON_ID");

ALTER TABLE FACT_SALARYPAID
ADD CONSTRAINT SALARYPAID_FK
FOREIGN KEY("SALARY_ID")
REFERENCES DIM_SALARY("SALARY_ID");

ALTER TABLE FACT_SALARYPAID
ADD CONSTRAINT TIME_SALARY_FK
FOREIGN KEY("TIME_ID")
REFERENCES DIM_TIME_SALARY("TIME_ID");

CREATE INDEX IDX_FK_PERSONID ON FACT_SALARYPAID(PERSON_ID);
CREATE INDEX IDX_FK_SALARYID ON FACT_SALARYPAID(SALARY_ID);
CREATE INDEX IDX_FK_TIMEID ON FACT_SALARYPAID(TIME_ID);
